//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.CartItems = new HashSet<CartItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Format { get; set; }
        public long ISBN { get; set; }
        public decimal Price { get; set; }
        public string img_path { get; set; }
        public int CategoryId { get; set; }
        public int AuthorId { get; set; }
        public Nullable<double> BookStar { get; set; }
        public System.DateTime PublicationYear { get; set; }
        public string Description { get; set; }
        public int QuantityInStock { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual Author Author { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartItem> CartItems { get; set; }
        public virtual Category Category { get; set; }
    }
}
